server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://rm-bp19k8vtd655i21r53o.mysql.rds.aliyuncs.com:3306/hmdatabase
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: TGX731875920


    hikari:
      maximum-pool-size: 20
      minimum-idle: 5

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create